openapi: 3.0.3
info:
  title: 'Device Manager'
  description: 'This api supports all the needs of a device management application.'
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8000'
paths:
  /api/login:
    post:
      summary: Login
      description: ''
      parameters:
        -
          in: query
          name: email
          description: 'Email do Usuário'
          example: laborum
          required: true
          schema:
            type: string
            description: 'Email do Usuário'
            example: laborum
        -
          in: query
          name: password
          description: 'Senha do Usuário'
          example: ut
          required: true
          schema:
            type: string
            description: 'Senha do Usuário'
            example: ut
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Autenticação
      security: []
  /api/register:
    post:
      summary: Registro
      description: ''
      parameters:
        -
          in: query
          name: name
          description: 'Nome do Usuário'
          example: sit
          required: true
          schema:
            type: string
            description: 'Nome do Usuário'
            example: sit
        -
          in: query
          name: email
          description: 'Email do Usuário'
          example: ab
          required: true
          schema:
            type: string
            description: 'Email do Usuário'
            example: ab
        -
          in: query
          name: password
          description: 'Senha do Usuário'
          example: consectetur
          required: true
          schema:
            type: string
            description: 'Senha do Usuário'
            example: consectetur
        -
          in: query
          name: password_confirmation
          description: 'Confirmação da senha do Usuário'
          example: optio
          required: true
          schema:
            type: string
            description: 'Confirmação da senha do Usuário'
            example: optio
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Autenticação
      security: []
  /api/logout:
    post:
      summary: Logout
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Autenticação
  /api/devices:
    get:
      summary: 'Todos dispositívos do usuário'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Dispositivos
    post:
      summary: 'Criação de dispositívo'
      description: ''
      parameters:
        -
          in: query
          name: name
          description: 'Nome do dispositivo'
          example: consequatur
          required: true
          schema:
            type: string
            description: 'Nome do dispositivo'
            example: consequatur
        -
          in: query
          name: type
          description: 'Tipo do dispositivo (1 = ON/OFF, 2 = LED RGB, 3 = DISPOSITIVO DE BRILHO)'
          example: 4
          required: true
          schema:
            type: integer
            description: 'Tipo do dispositivo (1 = ON/OFF, 2 = LED RGB, 3 = DISPOSITIVO DE BRILHO)'
            example: 4
        -
          in: query
          name: red
          description: 'Valor da cor vermelha (Caso seja LED)'
          example: 4
          required: false
          schema:
            type: integer
            description: 'Valor da cor vermelha (Caso seja LED)'
            example: 4
        -
          in: query
          name: green
          description: 'Valor da cor verde (Caso seja LED)'
          example: 2
          required: false
          schema:
            type: integer
            description: 'Valor da cor verde (Caso seja LED)'
            example: 2
        -
          in: query
          name: blue
          description: 'Valor da cor azul (Caso seja LED)'
          example: 8
          required: false
          schema:
            type: integer
            description: 'Valor da cor azul (Caso seja LED)'
            example: 8
        -
          in: query
          name: brightness
          description: 'Valor da luminosidade (Caso seja DISPOSITIVO DE BRILHO)'
          example: 14
          required: false
          schema:
            type: integer
            description: 'Valor da luminosidade (Caso seja DISPOSITIVO DE BRILHO)'
            example: 14
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Dispositivos
  '/api/devices/{id}':
    get:
      summary: 'Dispositivo Individual'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Dispositivos
    put:
      summary: 'Edição de dispositívo'
      description: ''
      parameters:
        -
          in: query
          name: name
          description: 'Nome do dispositivo'
          example: minus
          required: true
          schema:
            type: string
            description: 'Nome do dispositivo'
            example: minus
        -
          in: query
          name: type
          description: 'Tipo do dispositivo (1 = ON/OFF, 2 = LED RGB, 3 = DISPOSITIVO DE BRILHO)'
          example: 7
          required: true
          schema:
            type: integer
            description: 'Tipo do dispositivo (1 = ON/OFF, 2 = LED RGB, 3 = DISPOSITIVO DE BRILHO)'
            example: 7
        -
          in: query
          name: red
          description: 'Valor da cor vermelha (Caso seja LED)'
          example: 19
          required: false
          schema:
            type: integer
            description: 'Valor da cor vermelha (Caso seja LED)'
            example: 19
        -
          in: query
          name: green
          description: 'Valor da cor verde (Caso seja LED)'
          example: 20
          required: false
          schema:
            type: integer
            description: 'Valor da cor verde (Caso seja LED)'
            example: 20
        -
          in: query
          name: blue
          description: 'Valor da cor azul (Caso seja LED)'
          example: 14
          required: false
          schema:
            type: integer
            description: 'Valor da cor azul (Caso seja LED)'
            example: 14
        -
          in: query
          name: brightness
          description: 'Valor da luminosidade (Caso seja DISPOSITIVO DE BRILHO)'
          example: 15
          required: false
          schema:
            type: integer
            description: 'Valor da luminosidade (Caso seja DISPOSITIVO DE BRILHO)'
            example: 15
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Dispositivos
    delete:
      summary: 'Exclusão de dispositivo'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Dispositivos
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the device.'
        example: 17
        required: true
        schema:
          type: integer
tags:
  -
    name: Autenticação
    description: "\nRotas para gerenciamento de login de usuários"
  -
    name: Dispositivos
    description: "\nRotas para gerenciamento de dispositivos"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
